import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/layout/Navbar";
import Footer from "./component/layout/Footer";
import LayoutVisibility from "./component/layout/LayoutVisibility";
 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blockfortune",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
          <LayoutVisibility>
            <Navbar />
          </LayoutVisibility>

          {children}

          <LayoutVisibility>
            <Footer  />
          </LayoutVisibility>
        
      </body>
    </html>
  );
}
